"use client"
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from '@clerk/nextjs'
import {Cartcontext} from "./_context/cartcontext"
import { useState } from "react";

const inter = Roboto({ subsets: ["latin"] , weight:"700" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart,setcart] = useState([])

  return (
    <ClerkProvider>
      <Cartcontext.Provider value={{cart,setcart}}>
        <html lang="en">
          <body className={inter.className}>
            <Header/>
            {children}
            <Footer/>

          </body>
        </html>
      </Cartcontext.Provider>
    </ClerkProvider>
   
  );
}
